### ISSUE TITLE
Simulation is dependent on playback speed

### ISSUE THREAD

**Issue by Heybye44** [cheece/JiggleArmature#1]
When I play my animation in the viewport with frame dropping on the jiggles look realistic however when the animation is rendered, rendered with OpenGL, or played with no sync enabled the simulation appears stiff and jumpy.

**Comment by cheece** [comment]
yes, indeed the simulation is dependent on playback speed, and very sensitive on the frame rate, so it is in general bad idea to play the simulation in test mode with sync enabled,, different frame rate: different behavior,
