### ISSUE TITLE
2.8

### ISSUE THREAD

**Issue by SleeperG** [cheece/JiggleArmature#10]
Hello. I was just wondering if you'd be updating this add-on for 2.8? Although I had issues with it in 2.79 ( like my breast either flipping backwards or staying behind), I still liked using it. I hope you are planning to port this with tweaks of course. Thanks.

**Comment by cheece** [comment]
probably, i'd like, but i don't know when; regarding the simulation artifacts, the algorithm has some flaws that make it not stable under some conditions, it's on my todo list, for now the workaround i use is just to tweak the stiffness and damping so it behaves "ok"

**Comment by cheece** [comment]
stability issues should be fixed now

**Comment by benhenry96** [comment]
Hey Simon, any update on a 2.8 version? I tried converting it myself but lack the necessary knowledge to do so. I got it to at least show up in blender 2.8 but the reset state and set rest button seems to be bugged.

**Comment by cheece** [comment]
greetings, i just uploaded a new branch "blender-2.8",   check out

**Comment by SleeperG** [comment]
Thx for getting back to me.  So the panel shows up in 2.8? Have to admit I
haven't searched for it because in preferences it says it needs an update.
I'll certainly try your method. Thx.
