### ISSUE TITLE
Bone physics are fine in playback, no physics when baked.

### ISSUE THREAD

**Issue by RagdollZombie** [cheece/JiggleArmature#12]
I'm having an issue where I have the bone physics working fine in playback, but whenever I attempt to bake them into my animation, the bones in the baked result are stiff as if the physics weren't baked at all. I've tried all the different sync modes with the same results. I'm using Blender 2.79. What could be the problem here?

**Comment by cheece** [comment]
should be fixed now, let me know if the problem persists
