### ISSUE TITLE
Suggestions (Blender 2.8)

### ISSUE THREAD

**Issue by Irmitya** [cheece/JiggleArmature#14]
- [ ] Use `col.prop_search()` instead of `col.prop()` for entering `control_bone`. this will allow you to select from a valid list of bones, instead of copy/paste or manually typing a bone's name.

- [ ] Disable the control slider when the control bone is not entered. This property is unused without one, in which case no sense in having it active.

- [ ] Allow choosing a control bone from another rig. Otherwise, you have to edit the original rig specifically for using this addon. 

- [ ] Either a "use_self_control" BoolProperty or default to it when no other control bone is specified. 
What this would do is allow the bone to have manual *(and baked)* animation on the bone and blend in simulation, without having to manually assign the bone to itself as it's control bone.

- [ ] Use proper naming of properties in the UI.
The UI is set to use the default names from properties, and the property values mostly use either their default lowercase names or manually set lowercase_names. 
They should be named with Capital Letters and Spacing, like every other property in Blender.

- [ ] It would also be good to add descriptions to the properties,

 - [ ] Also, remove unused properties. 
jiggle_tp, and debug are properties shown in the UI but do absolutely NOTHING elsewhere in the code.  Maybe in your private version but not the one posted here on github. 

Aside from descriptions, _and use_self_control, (at this minute)_, 
I've done all of these in my version of this addon, so if you don't understand any of what I'm saying or want it already done, I can give it to you.

**Comment by cheece** [comment]
hello, thanks for the feedback!, i'll clean up the code for the next release

**Comment by iredmedia** [comment]
@Irmitya you should submit a PR! im sure he'd appreciate not having to solve these himself?

**Comment by Irmitya** [comment]
@iredmedia No
