### ISSUE TITLE
editing armature hierarchy can break jiggle bones

### ISSUE THREAD

**Issue by slsteve** [cheece/JiggleArmature#2]
if I decide I want to edit my armature (particularly changing parenting) after I've started creating jiggle bones, the jiggle bones no longer 'jiggle' after exiting edit mode.

if for whatever reason hierarchy changes can't be supported, can there at least be an option to clear out the jiggle data so one can start fresh on the armature? right now I have to delete the entire armature and start from scratch if i want to make changes.

thanks!

**Comment by cheece** [comment]
jiggle bones aren't supported on bones without parents, every jiggle bone must have a parent,, if you clear the parent of the jiggle bone, it won't work until you assign a parent to it
