### ISSUE TITLE
Modifier not adding in 2.79

### ISSUE THREAD

**Issue by shonuff3d** [cheece/JiggleArmature#5]
Working on moving over to 2.79, when adding the plugin it says that its add and copies to the appropriate folder in AppData, but the plugin never loads. 

Upon saving user settings, quitting, and reloading blender it will show the Jiggle modifier in the addons browser but shows it as addon missing.

![missing](https://user-images.githubusercontent.com/30003508/30029155-a2151c28-914d-11e7-995c-6a9be430dc43.jpg)

**Comment by treezi1004** [comment]
The problem is that its file name. This addon support till 2.77 which means @cheece need to check blender's new update and python's new update for updating.

To fix the problem temporarily, you have to change its file name to __init__ then it is good to use.

**Comment by cheece** [comment]
no idea, it still works for me on 2.79

**Comment by cheece** [comment]
you can also just copy the file JiggleArmature.py to the addons directory

**Comment by Reoxur** [comment]
**_Can confirm the addon works in in 2.79._**

**Comment by treezi1004** [comment]
Sure it does work.

but for me i had to do changing the name

i dont know why though.

![0000](https://user-images.githubusercontent.com/26009893/37042095-95669492-21c2-11e8-8899-979b23ca83dd.JPG)
![0001](https://user-images.githubusercontent.com/26009893/37042101-9915fab0-21c2-11e8-85fc-e6afda801826.JPG)

**Comment by cheece** [comment]
i see you have the addon inside a folder "JiggleArmature-master", that's the reason, if you want it to work without changing the name you should copy the file JiggleArmature.py directly in the addons folder

**Comment by treezi1004** [comment]
oh that actually worked haha thanks! lol so if we are installing addon through user preference, it has to have __init__.py.

i have never worked on blender addons so i did not know how blender load addons.

i think i will just stick with __init__ since quite a lot of models already using the script in folder.

Thank you for the addon and help 👍 🥇 i will donate you if i make some profit with mobile game with the model.
