### ISSUE TITLE
Unable to record keyframes

### ISSUE THREAD

**Issue by Atimlotus** [cheece/JiggleArmature#6]
I have been unable to get automatic keyframing to work with these jiggle bones.

I have a simple test rig with two bones, a parent bone with a child bone extruded from the parents tail and set as a jiggle bone.  When I press the play button the child bone seems to jiggle just fine, but it doesn't record any keyframes.  

**Note** : Auto-keyframing is working for non-jiggle bones.

Setup
--------------------------------------------
Blender Version : 2.79
Jiggle Scene - On
Child bone is set as a jiggle bone (no warnings / errors ), it has a parent bone.
Automatic keyframing is on, I've tried with and without key sets.
Timeline -> Frame -> Auto-Keyframing Mode - Set to Add & Replace

**Comment by cheece** [comment]
i'll work on that

**Comment by Atimlotus** [comment]
I think I found a work around for this while solving a different problem.  

In 3D-View, Pose -> Animation -> Bake Action ( I didn't know about this function before )

It appears to work with Visual Keying both checked and unchecked.

**Comment by Reoxur** [comment]
**_Can confirm the Bake Action works._**

**Comment by cheece** [comment]
bake button is back now in two forms, "Bake Selected" and "Bake All", find it in the scene tab
