### ISSUE TITLE
@persistent update() prints garbage in console

### ISSUE THREAD

**Issue by Atimlotus** [cheece/JiggleArmature#7]
Line 551: @persistent
Line 552: def update(scene, tm = False):
...
Line 558: print(scene.jiggle.test_mode)     <---- this prints garbage in the console

I was cleaning up an add on of my own that was calling bpy.context.scene.frame_set(...).  I thought it was a Blender issue, turns out it was this line in your add on printing messages in the console.

**Comment by cheece** [comment]
should be fixed now
