### ISSUE TITLE
Jiggle Armature's panel isan't showed

### ISSUE THREAD

**Issue by LuizKowalskiJr** [cheece/JiggleArmature#9]
I can't enable Jiggle Armature becouse the panel isan't showed for me. Only Jinggle Bone's panel

![jingle 1](https://user-images.githubusercontent.com/44177230/46972954-3bb21b00-d096-11e8-93aa-49aea5f4e6fa.png)

![jingle 2](https://user-images.githubusercontent.com/44177230/46972978-4f5d8180-d096-11e8-88cb-40e61adf569f.png)

**Comment by cheece** [comment]
enable it in the scene properties
